<?php require_once 'include/header.php';?>

<div class="privacy__page policy_new" >
    <div class="header-wrap">
        <div class="heading" >
            <h1>Privacy Policy</h1>
        </div>
    </div>
    <div class="section__wrapper" >
        <div class="page__wrapper" >
            
            <div class="page__wrapper-content">
                <p>Effective date: 2023-01-30 (launch date)</p>
                <h3>1. Introduction:</h3>
                <p> <a href="<?=HOST_URL?>">Websitespeedy.com</a> (“we”, “us”, or “our”) is committed to protecting the privacy of our users (“you” or “your”). This Privacy Policy describes how we collect, use, and share personal data, and outlines your rights regarding this data.</p>
                <h3>2. Definitions</h3>
                <ul class="page-wrapper-ul">
                    <li>SERVICE means the <a href="<?=HOST_URL?>">https://websitespeedy.com/</a> website operated by Website Speedy.</li>
                    <li>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                    <li>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li>COOKIES are small files stored on your device (computer or mobile device).</li>
                    <li>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
                    <li>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
                    <li>DATA SUBJECT is any living individual who is the subject of Personal Data.</li>
                    <li>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
                </ul>   
            <h3>3. Information Collection and Use</h3>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <ul class="page-wrapper-ul">
                <li>Information Provided Directly by You: We collect personal data that you voluntarily provide to us, such as your name, email address, phone number, and payment information. This information is collected when you create an account, purchase a product or service, or participate in surveys, contests, or other promotions.</li>
                <li>Information Received From Third Parties: We may receive personal data from third-party sources, such as social media platforms or referral websites, if you have allowed them to share your information.</li>
                <li>Information Collected Automatically
                    <ul class="page-wrapper-ul">
                        <li><strong>Device and Usage Data:</strong> We collect technical data about your device and usage of our website, including your IP address, browser type, operating system, and website usage information.</li>
                        <li><strong>Third-Party Widgets:</strong> Our website may include widgets, such as social media buttons, that collect personal data and track your use of our website.</li>
                        <li><strong>Cookies:</strong> We use cookies and other similar technologies to collect information about your preferences and to personalize your experience on our website. You can control the use of cookies through your browser settings.</li>
                    </ul>
                </li>
            </ul>
            <h3>4. Use of Data</h3>
            <p>Website Speedy uses the collected data for various purposes:</p>
            <ul class="page-wrapper-ul">
                <li>To provide customer support;</li>
                <li>To provide and improve our services;</li>
                <li>To personalize your experience on our website;</li>
                <li>To notify you about changes to our Service;</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so;</li>
                <li>To gather analysis or valuable information so that we can improve our Service;</li>
                <li>To monitor the usage of our Service;</li>
                <li>To detect, prevent and address technical issues;</li>
                <li>To fulfill any other purpose for which you provide it;</li>
                <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.;</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                <li>In any other way we may describe when you provide the information;</li>
                <li>For any other purpose with your consent.</li>
            </ul>
            <h3>5. Retention of Data</h3>
            <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
            
            <h3>6. Disclosure of Data</h3>
            <p>We may disclose personal information that we collect, or you provide:</p>
            <ul class="page-wrapper-ul">
                <li><strong>Disclosure for Law Enforcement:</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
                <li><strong>Business Transaction: </strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
                <li><strong>Other cases.</strong>We may disclose your information also:
                    <ul class="page-wrapper-ul">
                        <li>To our subsidiaries and affiliates;</li>
                        <li>To fulfill the purpose for which you provide it;</li>
                        <li>For any other purpose disclosed by us when you provide the information;</li>
                        <li>With your consent in any other cases;</li>
                        <li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
                    </ul>
                </li>
            </ul>
            <h3>7. Security of Data</h3>
            <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
            <h3>8. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>
            <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
            <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <a href="mailto:support@websitespeedy.com">support@websitespeedy.com</a>.</p>
            <p>In certain circumstances, you have the following data protection rights:</p>
            <ul class="page-wrapper-ul">
                <li>The right to access, update or to delete the information we have on you;</li>
                <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
                <li>The right to object. You have the right to object to our processing of your Personal Data;</li>
                <li>The right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
                <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
                <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
            </ul>
            <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</p>
            <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
            <h3>9. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h3>
            <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.</p>
            <p>According to CalOPPA we agree to the following:</p>
            <ul class="page-wrapper-ul">
                <li>Users can visit our site anonymously;</li>
                <li>Our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;</li>
                <li>Users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
                <li>Users are able to change their personal information by emailing us at <a href="mailto:support@websitespeedy.com">support@websitespeedy.com</a>.</li>
            </ul>

            <h3>10. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h3>
            <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:</p>
            <ul class="page-wrapper-ul">
                <li>What personal information we have about you. If you make this request, we will return to you:
                    <ul class="page-wrapper-ul">
                        <li>The categories of personal information we have collected about you.</li>
                        <li>The categories of sources from which we collect your personal information.</li>
                        <li>The business or commercial purpose for collecting or selling your personal information.</li>
                        <li>The categories of third parties with whom we share personal information.</li>
                        <li>The specific pieces of personal information we have collected about you.</li>
                        <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
                        <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
                    </ul>
                </li>
                <li><strong>To delete your personal information.</strong>If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</li>
                <li><strong>To stop selling your personal information.</strong>We don’t sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
                <br>Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.</li>
            </ul>
            <p>To exercise your California data protection rights described above, please send your request(s) by email: <a href="mailto:support@websitespeedy.com">support@websitespeedy.com</a>.</p>
            <p>Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website.</p>
            <h3>11. Analytics</h3>
            <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
            <h3>12. Behavioral Remarketing</h3>
            <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>

            <h3>13. Payments</h3>
            <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>

            <h3>14. Children’s Privacy</h3>
            <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>
            <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
            <h3>15. Changes to This Privacy Policy</h3>
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

            <h3>16. Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:support@websitespeedy.com">support@websitespeedy.com</a>.</p>
            </div>
                
        </div>
    </div>
</div>

<?php require_once 'include/footer.php';?>