on:
 push:
  branches:
   - main
name: Production Deploy
jobs:
  FTP-Deploy-Action:
   name: FTP-Deploy-Action
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3.1.0
     with:
      fetch-depth: 2
   - name: FTP-Deploy-Action
     uses: SamKirkland/FTP-Deploy-Action@3.1.1
     with:
      ftp-server: 24.199.105.142
      ftp-username: root
      ftp-password: makk@123Aa