name: Auto Deploy
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Digitalocean droplet
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: 24.199.105.142 #${{ secrets.HOST }}
          username: root #${{ secrets.USERNAME }}
          password: makk@123Aa #${{ secrets.PASSWORD }}
          port: 22 #${{ secrets.PORT }}
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/html
          # sftp args
          args: '-o ConnectTimeout=5'